/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MicroserviceCache {
  constructor(maxSize?: number | undefined | null, defaultTtlSeconds?: number | undefined | null)
  set(
    key: string,
    value: string,
    ttlSeconds?: number | undefined | null,
    tags?: Array<string> | undefined | null,
  ): boolean
  get(key: string): string | null
  delete(key: string): boolean
  getStats(): string
  getAllKeys(): Array<string>
  flush(): number
}
